version: "3"
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./api/:/api
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
        PORT: 3000
    ports: 
        - 3000:3000
    volumes: 
      - ./client/public:/client/public
      - ./client/src:/client/src
