name: Deploy Docker Image to AWS EC2

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
    types: [opened, synchronize]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        id: build-image
        uses: docker/build-push-action@v2
        with:
          context: ./api
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ github.repository }}:${{ github.sha }}


      - name: SSH into EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: 45.180.60.131/32
          username: fast-delivery-server
          key: ${{ secrets.AWS_EC2_INSTANCE_KEY }}
          port: 22
          script: |
            sudo docker stop fast-delivery_api || true
            sudo docker rm fast-delivery_api || true
            sudo docker pull ${{ steps.login-ecr.outputs.registry }}/${{ github.repository }}:${{ github.sha }}
            sudo docker run -d -p 80:80 --name fast-delivery_api ${{ steps.login-ecr.outputs.registry }}/${{ github.repository }}:${{ github.sha }}
