name: Docker Deploy

on:
  push:
    branches: [ develop ]

jobs:
  EC2-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t fast-delivery_api:latest ./api

      - name: Deploy to EC2
        uses: bitovi/github-actions-deploy-docker-to-ec2@v0.5.0
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_default_region: us-east-1
          image_name: fast-delivery_api
          image_tag: latest

