name: Deploy to EC2 Instance

on:
  push:
    branches: [develop]

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.AWS_EC2_INSTANCE_PASSWORD }}
        known_hosts: ${{ secrets.AWS_EC2_INSTANCE_KEY }}

    - name: Build and tag Docker image
      run: |
        docker build -t fast-delivery_api:latest ./api
        docker tag fast-delivery_api:latest 45.180.60.131/32:fast-delivery_api:latest

    - name: Load Docker image into EC2 instance
      run: |
        docker save fast-delivery_api:latest | ssh -i ${{ secrets.AWS_EC2_INSTANCE_KEY }} ec2-user@45.180.60.131/32 "docker load"

